---
engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true
  eslint:
    enabled: true
  scss-lint:
    enabled: true
ratings:
  paths:
    - Gemfile.lock
    - "**.js"
    - "**.rb"
    - "**.scss"
exclude_paths: []

